runtime: nodejs22
service: default

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.8
  min_pending_latency: 30ms
  max_pending_latency: automatic

env_variables:
  NODE_ENV: production
  PORT: 3010
  OPENROUTER_ENABLED: 'true'
  OPENROUTER_BASE_URL: 'https://openrouter.ai/api/v1'

handlers:
  - url: /api/.*
    secure: always
    script: auto

  - url: /.*
    secure: always
    script: auto

inbound_services:
  - warmup

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60
